<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ArmyJourney;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * BattleJourneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyJourneyRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ArmyJourney::class);
    }

    public function getNewReportsCount(int $cellId)
    {
        return $this->createQueryBuilder('aj')
            ->select('count(aj.id)')
            ->where('aj.destination = :cellId')
            ->setParameter('cellId', $cellId)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
