<?php

namespace AppBundle\Repository;

/**
 * ScheduledTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduledTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
