<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Platform;
use AppBundle\Entity\Unit;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends \Doctrine\ORM\EntityRepository
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new Mapping\ClassMetadata(Unit::class));
    }

    public function findInTraining(Platform $platform = null)
    {
        $qb = $this->createQueryBuilder('unit');
        $qb->where('unit.startBuild is not null');
        if ($platform !== null) {
            $qb->andWhere('unit.platform = :platform')
                ->setParameter('platform', $platform);
        }

        return $qb->getQuery()->getResult();
    }
}
