<?php

namespace AppBundle\Repository;

/**
 * UnitTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
