<?php

namespace AppBundle\Repository;
use AppBundle\Entity\UserTopic;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;

/**
 * UserTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTopicRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, UserTopic::class);
    }

//    public function findOneById(int $id)
//    {
//        return $this->createQueryBuilder('convo')
//            ->join('convo.topic', 't')
//            ->join('t.messages', 'm') //todo - remove both joins when fix messages
//            ->join('m.sender', 's') //todo - remove both joins when fix messages
//            ->addSelect('t')
//            ->addSelect('m')
//            ->addSelect('s')
//            ->where('convo.id = :id')
//            ->setParameter('id', $id)
//            ->getQuery()
//            ->getOneOrNullResult();
//    }

    public function findOneByUserAndTopic(int $userId, int $topicId)
    {
        return $this->createQueryBuilder('ut')
            ->join('ut.topic', 't')
//            ->join('t.messages', 'm')
//            ->join('m.sender', 's')
            ->addSelect('t')
//            ->addSelect('m')
//            ->addSelect('s')
            ->where('ut.user = :userId')
            ->andWhere('ut.topic = :topicId')
            ->setParameter('userId', $userId)
            ->setParameter('topicId', $topicId)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findAllByUser(int $userId)
    {
        return $this->createQueryBuilder('ut')
            ->join('ut.topic', 't')
//            ->join('t.sender', 's')
//            ->join('t.recipient', 'r')
            ->addSelect('t')
//            ->addSelect('s')
//            ->addSelect('r')
            ->where('ut.user = :userId')
            ->setParameter('userId', $userId)
            ->orderBy('t.updatedOn', 'DESC')
            ->getQuery()
            ->getResult();
    }

    public function getNewTopicsCount(int $userId)
    {
        return $this->createQueryBuilder('ut')
            ->select('count(ut.id)')
            ->where('ut.user = :userId')
            ->andWhere('ut.isRead = 0')
            ->setParameter('userId', $userId)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
